<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\Sight.IoC\Sight.IoC.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DryIoc" />
    <PackageReference Include="Autofac" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" VersionOverride="10.0.12" />
  </ItemGroup>
</Project>
