<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <CopyDependencies>true</CopyDependencies>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="System" />
    <Using Include="System.Collections.Generic" />
    <Using Include="System.Linq" />
    <Using Include="System.Text" />
    <Using Include="System.Threading.Tasks" />
    <Using Include="NUnit.Framework" />
    <Using Include="NUnit.Framework.Legacy.ClassicAssert" Alias="Assert" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="NunitXml.TestLogger" />
  </ItemGroup>
</Project>
