<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <CopyDependencies>false</CopyDependencies>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <PropertyGroup>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Authors>Arthur Ferre</Authors>
    <RepositoryUrl>https://github.com/LePtitDev/Sight.git</RepositoryUrl>
    <PackageProjectUrl>https://github.com/LePtitDev/Sight</PackageProjectUrl>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <Copyright>Copyright © Arthur Ferre 2022-2026</Copyright>
  </PropertyGroup>
</Project>
