<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <CopyDependencies>true</CopyDependencies>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="System" />
    <Using Include="System.Collections.Generic" />
    <Using Include="System.Linq" />
    <Using Include="System.Text" />
    <Using Include="System.Threading.Tasks" />
    <Using Include="BenchmarkDotNet.Attributes" />
    <Using Include="BenchmarkDotNet.Jobs" />
    <Using Include="BenchmarkDotNet.Running" />
    <Using Include="Sight.Benchmarks" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="$(MSBuildThisFileDirectory)Shared\**\*.cs">
      <Link>Shared\%(RecursiveDir)/%(FileName)%(Extension)</Link>
    </Compile>
  </ItemGroup>
</Project>
